spring:
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/datingApp}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:2005}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
jwt:
  #secret: ${JWT_SECRET}
  secret: ${JWT_SECRET:defaultSecretKeyForDevOnlyDoNotUseInProduction}
  expiration: 86400000

minio:
  endpoint: https://thebestapptppbezzppminio.loca.lt
  access-key: minioadmin
  secret-key: minioadmin

app:
  likes:
    free-daily-limit: 5
    premium-daily-limit: 100
  video:
    max-size-mb: 250
    max-duration-sec: 120
server:
  port: 8080
  connection-timeout: 120000
  tomcat:
    keep-alive-timeout: 120000
    threads:
      max: 200
    accept-count: 100